# Generated by Django 2.2.4 on 2020-12-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20201209_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='income',
        ),
    ]
